name: Node Build en test

on:
  push:
    branches: [master]

jobs:
  test_pull_request:
    runs-on: ${{matrix.os}}
    
    strategy:
      matrix:
        node-version: [16.x]
        os: [ubuntu-latest]
    
    steps:
      - uses: actions/checkout@v2
      - name: use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
      - run: npm ci
      - run: npm test
      - run: npm run build
      - name: upload artifact with JSON results
        uses: actions/upload-artifact@v3
        with:
          name: output
          path: output.json
